// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExprRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExprRequest) Reset() {
	*x = ExprRequest{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExprRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExprRequest) ProtoMessage() {}

func (x *ExprRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExprRequest.ProtoReflect.Descriptor instead.
func (*ExprRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

type ExprResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Oper          string                 `protobuf:"bytes,3,opt,name=Oper,proto3" json:"Oper,omitempty"`
	LastTask      int32                  `protobuf:"varint,4,opt,name=LastTask,proto3" json:"LastTask,omitempty"`
	Ans           float64                `protobuf:"fixed64,5,opt,name=Ans,proto3" json:"Ans,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Agent         int64                  `protobuf:"varint,7,opt,name=Agent,proto3" json:"Agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExprResponse) Reset() {
	*x = ExprResponse{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExprResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExprResponse) ProtoMessage() {}

func (x *ExprResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExprResponse.ProtoReflect.Descriptor instead.
func (*ExprResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *ExprResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ExprResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ExprResponse) GetOper() string {
	if x != nil {
		return x.Oper
	}
	return ""
}

func (x *ExprResponse) GetLastTask() int32 {
	if x != nil {
		return x.LastTask
	}
	return 0
}

func (x *ExprResponse) GetAns() float64 {
	if x != nil {
		return x.Ans
	}
	return 0
}

func (x *ExprResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExprResponse) GetAgent() int64 {
	if x != nil {
		return x.Agent
	}
	return 0
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\x05proto\"\r\n" +
	"\vExprRequest\"\xa6\x01\n" +
	"\fExprResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x12\n" +
	"\x04Oper\x18\x03 \x01(\tR\x04Oper\x12\x1a\n" +
	"\bLastTask\x18\x04 \x01(\x05R\bLastTask\x12\x10\n" +
	"\x03Ans\x18\x05 \x01(\x01R\x03Ans\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\x05R\x06Status\x12\x14\n" +
	"\x05Agent\x18\a \x01(\x03R\x05Agent2;\n" +
	"\x05Exprs\x122\n" +
	"\aGetExpr\x12\x12.proto.ExprRequest\x1a\x13.proto.ExprResponseB\n" +
	"Z\b../protob\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orchestrator_proto_goTypes = []any{
	(*ExprRequest)(nil),  // 0: proto.ExprRequest
	(*ExprResponse)(nil), // 1: proto.ExprResponse
}
var file_orchestrator_proto_depIdxs = []int32{
	0, // 0: proto.Exprs.GetExpr:input_type -> proto.ExprRequest
	1, // 1: proto.Exprs.GetExpr:output_type -> proto.ExprResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
