// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendExprRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExprRequest) Reset() {
	*x = SendExprRequest{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExprRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExprRequest) ProtoMessage() {}

func (x *SendExprRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExprRequest.ProtoReflect.Descriptor instead.
func (*SendExprRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

type SendExprResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Oper          string                 `protobuf:"bytes,3,opt,name=Oper,proto3" json:"Oper,omitempty"`
	LastTask      int32                  `protobuf:"varint,4,opt,name=LastTask,proto3" json:"LastTask,omitempty"`
	Ans           float64                `protobuf:"fixed64,5,opt,name=Ans,proto3" json:"Ans,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Agent         int64                  `protobuf:"varint,7,opt,name=Agent,proto3" json:"Agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExprResponse) Reset() {
	*x = SendExprResponse{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExprResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExprResponse) ProtoMessage() {}

func (x *SendExprResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExprResponse.ProtoReflect.Descriptor instead.
func (*SendExprResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SendExprResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SendExprResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SendExprResponse) GetOper() string {
	if x != nil {
		return x.Oper
	}
	return ""
}

func (x *SendExprResponse) GetLastTask() int32 {
	if x != nil {
		return x.LastTask
	}
	return 0
}

func (x *SendExprResponse) GetAns() float64 {
	if x != nil {
		return x.Ans
	}
	return 0
}

func (x *SendExprResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendExprResponse) GetAgent() int64 {
	if x != nil {
		return x.Agent
	}
	return 0
}

type ReceiveExprRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveExprRequest) Reset() {
	*x = ReceiveExprRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveExprRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveExprRequest) ProtoMessage() {}

func (x *ReceiveExprRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveExprRequest.ProtoReflect.Descriptor instead.
func (*ReceiveExprRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *ReceiveExprRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReceiveExprRequest) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type ReceiveExprResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveExprResponse) Reset() {
	*x = ReceiveExprResponse{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveExprResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveExprResponse) ProtoMessage() {}

func (x *ReceiveExprResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveExprResponse.ProtoReflect.Descriptor instead.
func (*ReceiveExprResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\forchestrator\"\x11\n" +
	"\x0fSendExprRequest\"\xaa\x01\n" +
	"\x10SendExprResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x12\n" +
	"\x04Oper\x18\x03 \x01(\tR\x04Oper\x12\x1a\n" +
	"\bLastTask\x18\x04 \x01(\x05R\bLastTask\x12\x10\n" +
	"\x03Ans\x18\x05 \x01(\x01R\x03Ans\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\x05R\x06Status\x12\x14\n" +
	"\x05Agent\x18\a \x01(\x03R\x05Agent\"<\n" +
	"\x12ReceiveExprRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result\"\x15\n" +
	"\x13ReceiveExprResponse2\xa6\x01\n" +
	"\x05Exprs\x12I\n" +
	"\bSendExpr\x12\x1d.orchestrator.SendExprRequest\x1a\x1e.orchestrator.SendExprResponse\x12R\n" +
	"\vReceiveExpr\x12 .orchestrator.ReceiveExprRequest\x1a!.orchestrator.ReceiveExprResponseB&Z$github.com/Se623/calc-full-app/protob\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orchestrator_proto_goTypes = []any{
	(*SendExprRequest)(nil),     // 0: orchestrator.SendExprRequest
	(*SendExprResponse)(nil),    // 1: orchestrator.SendExprResponse
	(*ReceiveExprRequest)(nil),  // 2: orchestrator.ReceiveExprRequest
	(*ReceiveExprResponse)(nil), // 3: orchestrator.ReceiveExprResponse
}
var file_orchestrator_proto_depIdxs = []int32{
	0, // 0: orchestrator.Exprs.SendExpr:input_type -> orchestrator.SendExprRequest
	2, // 1: orchestrator.Exprs.ReceiveExpr:input_type -> orchestrator.ReceiveExprRequest
	1, // 2: orchestrator.Exprs.SendExpr:output_type -> orchestrator.SendExprResponse
	3, // 3: orchestrator.Exprs.ReceiveExpr:output_type -> orchestrator.ReceiveExprResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
