// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: orchestrator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exprs_SendExpr_FullMethodName    = "/orchestrator.Exprs/SendExpr"
	Exprs_ReceiveExpr_FullMethodName = "/orchestrator.Exprs/ReceiveExpr"
)

// ExprsClient is the client API for Exprs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExprsClient interface {
	SendExpr(ctx context.Context, in *SendExprRequest, opts ...grpc.CallOption) (*SendExprResponse, error)
	ReceiveExpr(ctx context.Context, in *ReceiveExprRequest, opts ...grpc.CallOption) (*ReceiveExprResponse, error)
}

type exprsClient struct {
	cc grpc.ClientConnInterface
}

func NewExprsClient(cc grpc.ClientConnInterface) ExprsClient {
	return &exprsClient{cc}
}

func (c *exprsClient) SendExpr(ctx context.Context, in *SendExprRequest, opts ...grpc.CallOption) (*SendExprResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendExprResponse)
	err := c.cc.Invoke(ctx, Exprs_SendExpr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exprsClient) ReceiveExpr(ctx context.Context, in *ReceiveExprRequest, opts ...grpc.CallOption) (*ReceiveExprResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveExprResponse)
	err := c.cc.Invoke(ctx, Exprs_ReceiveExpr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExprsServer is the server API for Exprs service.
// All implementations must embed UnimplementedExprsServer
// for forward compatibility.
type ExprsServer interface {
	SendExpr(context.Context, *SendExprRequest) (*SendExprResponse, error)
	ReceiveExpr(context.Context, *ReceiveExprRequest) (*ReceiveExprResponse, error)
	mustEmbedUnimplementedExprsServer()
}

// UnimplementedExprsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExprsServer struct{}

func (UnimplementedExprsServer) SendExpr(context.Context, *SendExprRequest) (*SendExprResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendExpr not implemented")
}
func (UnimplementedExprsServer) ReceiveExpr(context.Context, *ReceiveExprRequest) (*ReceiveExprResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveExpr not implemented")
}
func (UnimplementedExprsServer) mustEmbedUnimplementedExprsServer() {}
func (UnimplementedExprsServer) testEmbeddedByValue()               {}

// UnsafeExprsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExprsServer will
// result in compilation errors.
type UnsafeExprsServer interface {
	mustEmbedUnimplementedExprsServer()
}

func RegisterExprsServer(s grpc.ServiceRegistrar, srv ExprsServer) {
	// If the following call pancis, it indicates UnimplementedExprsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exprs_ServiceDesc, srv)
}

func _Exprs_SendExpr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExprRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExprsServer).SendExpr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exprs_SendExpr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExprsServer).SendExpr(ctx, req.(*SendExprRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exprs_ReceiveExpr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveExprRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExprsServer).ReceiveExpr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exprs_ReceiveExpr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExprsServer).ReceiveExpr(ctx, req.(*ReceiveExprRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Exprs_ServiceDesc is the grpc.ServiceDesc for Exprs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exprs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.Exprs",
	HandlerType: (*ExprsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendExpr",
			Handler:    _Exprs_SendExpr_Handler,
		},
		{
			MethodName: "ReceiveExpr",
			Handler:    _Exprs_ReceiveExpr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
